[env]
TERM = "xterm-256color"

[window]
blur = true
opacity = 1.00
decorations = "none"

[window.padding]
x = 5
y = 5

[font]
size = 11.3
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "bold_italic" }

[colors.primary]
background = "#212122"
foreground = "#cdd6f4"

[scrolling]
history = 5000
multiplier = 20

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
