general.import = [" ~/.config/alacritty/themes/light.toml "]
# general.import = [" ~/.config/alacritty/themes/dark.toml "]
# general.import = ["~/.config/alacritty/color.toml"]

[window]
# opacity = 0.95
# decorations = "Full"
decorations = "none"
# decorations_theme_variant = "Dark"

[window.padding]
x = 0
y = 0

[font]
size = 13.0

# JetBrainsMono / Iosevka Nerd Font
[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Regular"

[font.italic]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Regular"


[colors.primary]
background = "#212122"
foreground = "#cdd6f4"

# [colors.primary]
# foreground = "#000000"
# background = "#ffffff"

[scrolling]
history = 5000
multiplier = 10

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  # { key = "V", mods = "Control|Shift", action = "Paste" },
  # { key = "C", mods = "Control|Shift", action = "Copy" },
  # { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[env]
TERM = "xterm-256color"
