[ general ]
# import = ["~/.config/alacritty/themes/gruvbox.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 1.00
decorations = "none"

[window.padding]
x = 0
y = 0

# [font]
# size = 11.3
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# bold = { family = "JetBrainsMono Nerd Font", style = "bold" }
# italic = { family = "JetBrainsMono Nerd Font", style = "italic" }
# bold_italic = { family = "JetBrainsMono Nerd Font", style = "bold_italic" }

[font]
size = 12.3
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Regular" }
italic = { family = "Iosevka Nerd Font", style = "Regular" }
bold_italic = { family = "Iosevka Nerd Font", style = "Regular" }

[colors.primary]
background = "#212122"
foreground = "#cdd6f4"

[scrolling]
history = 5000
multiplier = 20

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]
